function task = generate_binary_reversal_task( ...
    nTrials, blockLength, rewardProbabilities, randomSeed)
%GENERATE_BINARY_REVERSAL_TASK Create a reproducible full-feedback task.
%   TASK = GENERATE_BINARY_REVERSAL_TASK(NTRIALS, BLOCKLENGTH, PROBS, SEED)
%   alternates between the two probabilities in PROBS every BLOCKLENGTH
%   trials. TASK.OUTCOME is 1 when option 1 is rewarded and 0 when option 0
%   is rewarded.

validateattributes(nTrials, {'numeric'}, ...
    {'scalar', 'integer', 'positive'}, mfilename, 'nTrials');
validateattributes(blockLength, {'numeric'}, ...
    {'scalar', 'integer', 'positive'}, mfilename, 'blockLength');
validateattributes(rewardProbabilities, {'numeric'}, ...
    {'vector', 'numel', 2, '>=', 0, '<=', 1}, ...
    mfilename, 'rewardProbabilities');
validateattributes(randomSeed, {'numeric'}, ...
    {'scalar', 'integer', 'nonnegative'}, mfilename, 'randomSeed');

rewardProbabilities = rewardProbabilities(:)';
trial = (1:nTrials)';
block = floor((trial - 1) ./ blockLength) + 1;
probabilityIndex = mod(block - 1, 2) + 1;
probabilityOption1 = rewardProbabilities(probabilityIndex)';

rng(randomSeed, 'twister');
outcome = double(rand(nTrials, 1) < probabilityOption1);

task = struct( ...
    'trial', trial, ...
    'block', block, ...
    'probabilityOption1', probabilityOption1, ...
    'outcome', outcome, ...
    'reversalTrial', find([false; diff(probabilityOption1) ~= 0]));
end
