function result = simulate_active_inference_tmaze( ...
    nTrials, randomSeed, actionPrecision, cueIsInformative)
%SIMULATE_ACTIVE_INFERENCE_TMAZE Run a compact cue-safe-risky MDP.
%   RESULT = SIMULATE_ACTIVE_INFERENCE_TMAZE(N, SEED, ALPHA, INFORMATIVE)
%   simulates N trials using SPM's MDP solver. INFORMATIVE controls whether
%   cue outcomes distinguish the two hidden reward contexts. The agent
%   always evaluates epistemic value, but an uninformative cue cannot reduce
%   uncertainty.

validateattributes(nTrials, {'numeric'}, ...
    {'scalar', 'integer', 'positive'}, mfilename, 'nTrials');
validateattributes(randomSeed, {'numeric'}, ...
    {'scalar', 'integer', 'nonnegative'}, mfilename, 'randomSeed');
validateattributes(actionPrecision, {'numeric'}, ...
    {'scalar', 'positive'}, mfilename, 'actionPrecision');
validateattributes(cueIsInformative, {'logical'}, ...
    {'scalar'}, mfilename, 'cueIsInformative');

rng(randomSeed, 'twister');

% Outcome model A: columns are eight hidden states (four locations crossed
% with two reward contexts). Rows are observable outcomes.
highRewardProbability = 0.75;
lowRewardProbability = 1 - highRewardProbability;
A{1} = [ ...
    1 1 0 0 0 0 0 0; ...
    0 0 1 1 0 0 0 0; ...
    0 0 0 0 highRewardProbability lowRewardProbability 0 0; ...
    0 0 0 0 lowRewardProbability highRewardProbability 0 0; ...
    0 0 0 0 0 0 1 0; ...
    0 0 0 0 0 0 0 1];

% In the control condition both cue outcomes are equally likely in either
% context, so visiting the cue has no expected information gain.
if ~cueIsInformative
    A{1}(5:6, 7:8) = 0.5;
end

% Transition model B: actions lead to center, safe, risky, or cue locations.
B{1}(:, :, 1) = [ ...
    1 0 0 0 0 0 1 0; 0 1 0 0 0 0 0 1; ...
    0 0 1 0 0 0 0 0; 0 0 0 1 0 0 0 0; ...
    0 0 0 0 1 0 0 0; 0 0 0 0 0 1 0 0; ...
    0 0 0 0 0 0 0 0; 0 0 0 0 0 0 0 0];
B{1}(:, :, 2) = [ ...
    0 0 0 0 0 0 0 0; 0 0 0 0 0 0 0 0; ...
    1 0 1 0 0 0 1 0; 0 1 0 1 0 0 0 1; ...
    0 0 0 0 1 0 0 0; 0 0 0 0 0 1 0 0; ...
    0 0 0 0 0 0 0 0; 0 0 0 0 0 0 0 0];
B{1}(:, :, 3) = [ ...
    0 0 0 0 0 0 0 0; 0 0 0 0 0 0 0 0; ...
    0 0 1 0 0 0 0 0; 0 0 0 1 0 0 0 0; ...
    1 0 0 0 1 0 1 0; 0 1 0 0 0 1 0 1; ...
    0 0 0 0 0 0 0 0; 0 0 0 0 0 0 0 0];
B{1}(:, :, 4) = [ ...
    0 0 0 0 0 0 0 0; 0 0 0 0 0 0 0 0; ...
    0 0 1 0 0 0 0 0; 0 0 0 1 0 0 0 0; ...
    0 0 0 0 1 0 0 0; 0 0 0 0 0 1 0 0; ...
    1 0 0 0 0 0 1 0; 0 1 0 0 0 0 0 1];

% Preferences: a modest safe reward, more extreme risky outcomes, and a small
% cue cost make information gathering useful only when it resolves context.
C{1} = [0 1 6 -4 -0.5 -0.5]';

% Equal prior probability of the two contexts at the center location.
D{1} = kron([0.5 0 0 0], [1 1])';

% Ten two-step policies: remain, choose directly, or inspect the cue first.
V = [ ...
    1 1 1 1 2 3 4 4 4 4; ...
    1 2 3 4 2 3 1 2 3 4];

mdp = struct;
mdp.V = V;
mdp.A = A;
mdp.B = B;
mdp.C = C;
mdp.D = D;
mdp.s = 1;
mdp.eta = 0.5;
mdp.beta = 1;
mdp.alpha = actionPrecision;
mdp = spm_MDP_check(mdp);

% Use one reversal halfway through the run: context 1 then context 2.
context = ones(1, nTrials);
context(floor(nTrials / 2) + 1:end) = 2;

MDP = mdp;
[MDP(1:nTrials)] = deal(mdp);
for trialIndex = 1:nTrials
    MDP(trialIndex).s = context(trialIndex);
    MDP(trialIndex).alpha = actionPrecision;
    MDP(trialIndex).beta = 1;
end

MDP = spm_MDP_VB_X(MDP);

firstAction = NaN(1, nTrials);
actionProbability = NaN(4, nTrials);
finalOutcome = NaN(1, nTrials);
for trialIndex = 1:nTrials
    firstAction(trialIndex) = MDP(trialIndex).u(1);
    actionProbability(:, trialIndex) = MDP(trialIndex).P(:, 1);
    finalOutcome(trialIndex) = MDP(trialIndex).o(1, end);
end

result = struct( ...
    'firstAction', firstAction, ...
    'actionProbability', actionProbability, ...
    'finalOutcome', finalOutcome, ...
    'context', context, ...
    'actionNames', {{'Stay', 'Safe', 'Risky', 'Cue'}}, ...
    'cueIsInformative', cueIsInformative, ...
    'mdp', MDP);
end
